project:
  type: website

website:
  title: "My Personal Space"
  navbar:
    left:
      - href: index.qmd
        text: Página Inícial
      - href: curriculo.qmd
        text: Currículo
      - href: projetos.qmd
        text: Projetos
      - href: contactos.qmd
        text: Contactos
  page-footer: "© 2025 Marcelo Brasiela"
  
format:
    html:
      theme: cosmo
      css: styles.css 
      
  

